### ISSUE TITLE
hi yunyu,it doesn't work when i upgrade vertx 3.5.0

### ISSUE THREAD

**Issue by angviza** [yunyu/vertx-console#2]

**Comment by yunyu** [comment]
From what I've seen, it's due to an issue with BodyHandler that was fixed in https://github.com/vert-x3/vertx-web/commit/23e10d6a4eca3774e040fcb3fc1e5684ea41759c. I'm personally holding off upgrading until 3.5.1.

**Comment by yunyu** [comment]
Going to reopen as it's still technically an issue. Due to the various issues that exist in Vert,x-web 3.5.0 and have been fixed in the master branch, I don't consider the current Vert.x-web release to be production-ready.

**Comment by yunyu** [comment]
https://github.com/yunyu/vertx-console/commit/36a06f2b395899076e1620717ad095debb2909c6
